### ISSUE TITLE
Merge plugins infrastructure into this project

### ISSUE THREAD

**Issue by metacosm** [halkyonio/operator-framework#2]
You cannot use plugins without using this project so it doesn't really make sense to have two separate projects. The only reason why it might make sense *to not merge* is if we want to keep the core framework "pure" of Halkyon-related concepts but there are already leaks and there is no obvious benefit or reuse use case at this time.

What do you think @cmoulliard ?

**Comment by cmoulliard** [comment]
This project also includes utility functions used by the operator halkyon - https://github.com/halkyonio/operator-framework/blob/master/env.go#L23 
So why would you like to merge with plugins ?

**Comment by metacosm** [comment]
I don't understand your point, @cmoulliard.
